### ISSUE TITLE
use GD::Image is required to avoid compile error.

### ISSUE THREAD

**Issue by perlsky** [mbeijen/GD-Barcode#4]
use GD::Image;
is required to avoid compile error because line 302 shows as following.
    my $oOutImg   = GD::Image->new(

**Comment by mbeijen** [comment]
Hi @perlsky , I'm not sure what you mean.

I can use the code perfectly fine without an explicit `use GD::Image;` - see for instance tests in https://github.com/mbeijen/GD-Barcode/blob/main/t/qrcode-image.t

Please feel free to reopen with sample code explaining your problem!
