### ISSUE TITLE
QR Code Geneartion Error

### ISSUE THREAD

**Issue by pk0482** [mbeijen/GD-Barcode#5]
Dear Mbeijen,

I have written a script which generates QR Code based on the string I need using `GD::Barcode::QRcode` module with version 2 and error correction level Q. So what I have noticed is that when I use alphanumeric string with 29 characters the QR code is perfectly generated but even when I increase by a character the I get below error

```
Overflow error. version 2
total bits: 178  max bits: 176
```

Here is the string which I have used `1J0001827182307260101103201:ZZ`

So I further looked at the core module and tried to modify the maxDataBits to 178 at below line to get it working

https://github.com/mbeijen/GD-Barcode/blob/main/lib/GD/Barcode/QRcode.pm#L360

but the genereated QR code doesn't work. So looks like it is not just as simple as fixing the data length instead the qr code generation depends on lot of other factors.

Thanks
PK

**Comment by mbeijen** [comment]
Indeed, with v2 I get the overflow error. However I can generate V1 QR Codes with your supplied data or other longer strings just fine. 

Please understand this is a very old module which is heavily in maintenance mode. So the V2 QRs had this issue apparently for over 20 years. I'm not indending on fixing this issue.

My advise:

 - Use a v1 QRCode, which does not have this issue
 - if you somehow MUST use V2, find another way to generate a QR code :-)
 
 Pull requests to fix this issue are welcomed!
